 <?php include 'navbar.php'; 
 include 'carousel.php';?>
  	<div class="container-fluid">
  		<div class="margin-text">
 	<h1 class="title">PUBLICATIONS</h1>
 		<p>All papers which are recommended for acceptance by the Technical Program Committee, will be included in the Proceedings of the Conference, provided (i) all the recommendations of the reviewers are incorporated in the final manuscript, (ii) at least one of the authors registers for the conference and (iii) the paper is presented in person, at the Conference. The Proceedings of INDICON2018, will be submitted to IEEE for possible inclusion in IEEExplore &ndash; this will require a further round of reviews at the discretion of the IEEE. The Proceedings of all previous editions of INDICON have been included in <a target="_blank" href="https://ieeexplore.ieee.org/search/searchresult.jsp?queryText=(%2522Publication%20Title%2522:INDICON)&amp;matchBoolean=true&amp;searchField=Search_All">IEEExplore</a> and indexed by <a target="_blank" href="https://www.scopus.com/results/results.uri?sort=plf-f&amp;src=s&amp;sid=91c459dcede1c3cd89ed83566ea0831b&amp;sot=a&amp;sdt=a&amp;sl=13&amp;s=CONF%28INDICON%29&amp;origin=searchadvanced&amp;editSaveSearch=&amp;txGid=564d254e0b729ff98d4a6d99417f179d">SCOPUS</a>.</p>
<p>All papers submitted before the deadlines will be sent to the reviewers as and when they are received and the decisions notified to the authors. Hence, authors of those papers submitted closer to the deadline will receive their decisions later. The guidelines for preparing the manuscript can be found elsewhere on this website. The management of manuscripts is automated and will be handled through <a target="_blank" href="https://edas.info/">EDAS</a>. Hence, all prospective authors are required to have a EDAS login. If you have submitted any manuscript through EDAS previously (either for a Conference or a Journal), the same login credentials can be used. Else, you may register at <a target="_blank" href="https://edas.info/newPerson.php?noauth=1&amp;rurl=aHR0cHM6Ly9lZGFzLmluZm8vPw%3D%3D">this</a> link. Once you have registered as an author, the manuscript submission page can be accessed <a target="_blank" href="http://edas.info/N24425">here</a>. </p>
 	</div>
</div>
 <?php include 'footer.php'; ?>